apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaledobject
  namespace: image-processor
spec:
  scaleTargetRef:
    name: worker
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: redis-streams
      metadata:
        address: redis:6379
        stream: image-jobs
        consumerGroup: workers
        lagCount: "5"
