apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: image-processor
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: image-processor
            targetRevision: HEAD
            autoSync: "true"
            prune: "true"
          - environment: staging
            namespace: image-processor-staging
            targetRevision: main
            autoSync: "true"
            prune: "true"
          - environment: prod
            namespace: image-processor-prod
            targetRevision: main
            autoSync: "false"
            prune: "false"
  
  template:
    metadata:
      name: image-processor-{{environment}}
      labels:
        environment: '{{environment}}'
    spec:
      project: default
      
      source:
        repoURL: https://github.com/timkrebs/go-microservice.git
        targetRevision: '{{targetRevision}}'
        path: deployments/kubernetes/overlays/{{environment}}
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      
      syncPolicy:
        {{#autoSync}}
        automated:
          prune: {{prune}}
          selfHeal: true
          allowEmpty: false
        {{/autoSync}}
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
