apiVersion: v1
kind: Secret
metadata:
  name: image-processor-secrets
  namespace: image-processor
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  POSTGRES_PASSWORD: "postgres"
  REDIS_PASSWORD: ""
